# Generated by Django 4.2.9 on 2025-10-20 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        (
            "services",
            "0003_alter_bookingsettings_options_alter_category_options_and_more",
        ),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={
                "ordering": ["-is_default", "-created_at"],
                "verbose_name": "Adres",
                "verbose_name_plural": "Adresler",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentmethod",
            options={
                "ordering": ["-is_default", "-created_at"],
                "verbose_name": "Ödeme Yöntemi",
                "verbose_name_plural": "Ödeme Yöntemleri",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Kullanıcı",
                "verbose_name_plural": "Kullanıcılar",
            },
        ),
        migrations.AlterField(
            model_name="address",
            name="apartment_no",
            field=models.CharField(blank=True, max_length=20, verbose_name="Daire No"),
        ),
        migrations.AlterField(
            model_name="address",
            name="building_no",
            field=models.CharField(blank=True, max_length=20, verbose_name="Bina No"),
        ),
        migrations.AlterField(
            model_name="address",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Oluşturulma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="services.district",
                verbose_name="Bölge",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="floor",
            field=models.CharField(blank=True, max_length=10, verbose_name="Kat"),
        ),
        migrations.AlterField(
            model_name="address",
            name="full_address",
            field=models.TextField(verbose_name="Tam Adres"),
        ),
        migrations.AlterField(
            model_name="address",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="Varsayılan"),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Posta Kodu"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="title",
            field=models.CharField(
                help_text="e.g., Home, Office",
                max_length=100,
                verbose_name="Adres Başlığı",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Güncellenme Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kullanıcı",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="card_brand",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Kart Markası"
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="card_token",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Kart Token"
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="cardholder_name",
            field=models.CharField(max_length=100, verbose_name="Kart Sahibi Adı"),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Oluşturulma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="expiry_month",
            field=models.CharField(max_length=2, verbose_name="Son Kullanma Ay"),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="expiry_year",
            field=models.CharField(max_length=4, verbose_name="Son Kullanma Yıl"),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif"),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="Varsayılan"),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="last_four_digits",
            field=models.CharField(max_length=4, verbose_name="Son 4 Hane"),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="payment_type",
            field=models.CharField(
                choices=[("card", "Credit/Debit Card")],
                default="card",
                max_length=20,
                verbose_name="Ödeme Tipi",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Güncellenme Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_methods",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kullanıcı",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Kayıt Tarihi"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="E-posta"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False, verbose_name="E-posta Doğrulandı"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="Telefon",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_verified",
            field=models.BooleanField(default=False, verbose_name="Telefon Doğrulandı"),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Güncellenme Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("admin", "Admin"),
                    ("technician", "Technician"),
                ],
                default="customer",
                max_length=20,
                verbose_name="Kullanıcı Tipi",
            ),
        ),
    ]
