# Generated by Django 4.2.9 on 2025-10-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="min_days_between_pickup_delivery",
            field=models.IntegerField(
                default=7,
                help_text="Minimum days required between pickup and delivery dates",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="requires_pickup_delivery",
            field=models.BooleanField(
                default=False,
                help_text="If true, requires separate pickup and delivery dates (e.g., carpet cleaning)",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="requires_time_selection",
            field=models.BooleanField(
                default=False,
                help_text="If true, customers must select a time slot (e.g., sofa cleaning)",
            ),
        ),
    ]
