# Generated by Django 4.2.9 on 2025-10-19 23:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_category_min_days_between_pickup_delivery_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookingsettings",
            options={
                "verbose_name": "Rezervasyon Ayarları",
                "verbose_name_plural": "Rezervasyon Ayarları",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["order_priority", "name"],
                "verbose_name": "Kategori",
                "verbose_name_plural": "Kategoriler",
            },
        ),
        migrations.AlterModelOptions(
            name="district",
            options={
                "ordering": ["order_priority", "name"],
                "verbose_name": "Bölge",
                "verbose_name_plural": "Bölgeler",
            },
        ),
        migrations.AlterModelOptions(
            name="holiday",
            options={
                "ordering": ["date"],
                "verbose_name": "Tatil",
                "verbose_name_plural": "Tatiller",
            },
        ),
        migrations.AlterModelOptions(
            name="pricing",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Fiyatlandırma",
                "verbose_name_plural": "Fiyatlandırmalar",
            },
        ),
        migrations.AlterModelOptions(
            name="subtype",
            options={
                "ordering": ["order_priority", "name"],
                "verbose_name": "Alt Kategori",
                "verbose_name_plural": "Alt Kategoriler",
            },
        ),
        migrations.AlterModelOptions(
            name="workinghours",
            options={
                "ordering": ["weekday"],
                "verbose_name": "Çalışma Saatleri",
                "verbose_name_plural": "Çalışma Saatleri",
            },
        ),
        migrations.AddField(
            model_name="subtype",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Icon class or emoji",
                max_length=50,
                verbose_name="İkon",
            ),
        ),
        migrations.AddField(
            model_name="subtype",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="subtypes/", verbose_name="Resim"
            ),
        ),
        migrations.AlterField(
            model_name="bookingsettings",
            name="cancellation_fee_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Percentage of total as cancellation fee (0-100)",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="İptal Ücreti %",
            ),
        ),
        migrations.AlterField(
            model_name="bookingsettings",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Oluşturulma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="bookingsettings",
            name="default_service_end_time",
            field=models.TimeField(
                default="00:00",
                help_text="Default service end time (00:00 = midnight)",
                verbose_name="Varsayılan Hizmet Bitiş Saati",
            ),
        ),
        migrations.AlterField(
            model_name="bookingsettings",
            name="default_service_start_time",
            field=models.TimeField(
                default="08:00",
                help_text="Default service start time (08:00)",
                verbose_name="Varsayılan Hizmet Başlangıç Saati",
            ),
        ),
        migrations.AlterField(
            model_name="bookingsettings",
            name="late_cancellation_fee_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Additional fee for cancellations within notice period",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Geç İptal Ücreti %",
            ),
        ),
        migrations.AlterField(
            model_name="bookingsettings",
            name="min_cancellation_notice_hours",
            field=models.IntegerField(
                default=2,
                help_text="Minimum hours before booking to allow cancellation (default: 2)",
                verbose_name="Min. İptal Bildirimi (Saat)",
            ),
        ),
        migrations.AlterField(
            model_name="bookingsettings",
            name="min_reschedule_notice_hours",
            field=models.IntegerField(
                default=2,
                help_text="Minimum hours before booking to allow rescheduling (default: 2)",
                verbose_name="Min. Yeniden Planlama Bildirimi (Saat)",
            ),
        ),
        migrations.AlterField(
            model_name="bookingsettings",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Güncellenme Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Oluşturulma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, verbose_name="Açıklama"),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Icon class or emoji",
                max_length=50,
                verbose_name="İkon",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="categories/", verbose_name="Resim"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif"),
        ),
        migrations.AlterField(
            model_name="category",
            name="min_days_between_pickup_delivery",
            field=models.IntegerField(
                default=7,
                help_text="Minimum days required between pickup and delivery dates",
                verbose_name="Alım-Teslim Arası Min. Gün",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Kategori Adı"),
        ),
        migrations.AlterField(
            model_name="category",
            name="order_priority",
            field=models.IntegerField(
                default=0,
                help_text="Lower numbers appear first",
                verbose_name="Sıralama Önceliği",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="pricing_type",
            field=models.CharField(
                choices=[
                    ("per_sqm", "Per Square Meter"),
                    ("per_item", "Per Item"),
                    ("per_seat", "Per Seat"),
                ],
                max_length=20,
                verbose_name="Fiyatlandırma Tipi",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="requires_pickup_delivery",
            field=models.BooleanField(
                default=False,
                help_text="If true, requires separate pickup and delivery dates (e.g., carpet cleaning)",
                verbose_name="Alım-Teslim Gerekli",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="requires_time_selection",
            field=models.BooleanField(
                default=False,
                help_text="If true, customers must select a time slot (e.g., sofa cleaning)",
                verbose_name="Saat Seçimi Gerekli",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Kısa Ad"),
        ),
        migrations.AlterField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Güncellenme Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Oluşturulma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="delivery_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Teslimat Ücreti",
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif"),
        ),
        migrations.AlterField(
            model_name="district",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Bölge Adı"
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="order_priority",
            field=models.IntegerField(
                default=0,
                help_text="Lower numbers appear first",
                verbose_name="Sıralama Önceliği",
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Güncellenme Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Oluşturulma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="date",
            field=models.DateField(unique=True, verbose_name="Tarih"),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Tatil Adı"),
        ),
        migrations.AlterField(
            model_name="pricing",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Temel Fiyat",
            ),
        ),
        migrations.AlterField(
            model_name="pricing",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Oluşturulma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="pricing",
            name="currency",
            field=models.CharField(
                default="TRY", max_length=3, verbose_name="Para Birimi"
            ),
        ),
        migrations.AlterField(
            model_name="pricing",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="İndirim %",
            ),
        ),
        migrations.AlterField(
            model_name="pricing",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif"),
        ),
        migrations.AlterField(
            model_name="pricing",
            name="subtype",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricing",
                to="services.subtype",
                verbose_name="Alt Kategori",
            ),
        ),
        migrations.AlterField(
            model_name="pricing",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Güncellenme Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="pricing",
            name="valid_from",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Geçerlilik Başlangıcı"
            ),
        ),
        migrations.AlterField(
            model_name="pricing",
            name="valid_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Geçerlilik Bitişi"
            ),
        ),
        migrations.AlterField(
            model_name="subtype",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtypes",
                to="services.category",
                verbose_name="Kategori",
            ),
        ),
        migrations.AlterField(
            model_name="subtype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Oluşturulma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="subtype",
            name="description",
            field=models.TextField(blank=True, verbose_name="Açıklama"),
        ),
        migrations.AlterField(
            model_name="subtype",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif"),
        ),
        migrations.AlterField(
            model_name="subtype",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Alt Kategori Adı"),
        ),
        migrations.AlterField(
            model_name="subtype",
            name="order_priority",
            field=models.IntegerField(default=0, verbose_name="Sıralama Önceliği"),
        ),
        migrations.AlterField(
            model_name="subtype",
            name="slug",
            field=models.SlugField(verbose_name="Kısa Ad"),
        ),
        migrations.AlterField(
            model_name="subtype",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Güncellenme Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="closing_time",
            field=models.TimeField(
                default="00:00",
                help_text="Default: 00:00 (midnight)",
                verbose_name="Kapanış Saati",
            ),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Oluşturulma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="is_working_day",
            field=models.BooleanField(default=True, verbose_name="Çalışma Günü"),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="max_bookings_per_slot",
            field=models.IntegerField(
                default=5,
                help_text="Maximum concurrent bookings",
                verbose_name="Slot Başına Max. Rezervasyon",
            ),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="opening_time",
            field=models.TimeField(
                default="08:00", help_text="Default: 08:00", verbose_name="Açılış Saati"
            ),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="slot_duration_minutes",
            field=models.IntegerField(
                default=60,
                help_text="Duration of each time slot",
                verbose_name="Slot Süresi (Dakika)",
            ),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Güncellenme Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="weekday",
            field=models.IntegerField(
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                unique=True,
                verbose_name="Gün",
            ),
        ),
    ]
