# Generated by Django 4.2.9 on 2025-10-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactFormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Ad Soyad")),
                ("email", models.EmailField(max_length=254, verbose_name="E-posta")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                ("message", models.TextField(verbose_name="Mesaj")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Okundu mu?"),
                ),
                (
                    "is_replied",
                    models.BooleanField(default=False, verbose_name="Cevaplandı mı?"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Adresi"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Gönderilme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "İletişim Formu",
                "verbose_name_plural": "İletişim Formları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="Halı Yıkama", max_length=200, verbose_name="Site Adı"
                    ),
                ),
                (
                    "site_description",
                    models.TextField(blank=True, verbose_name="Site Açıklaması"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        max_length=254, verbose_name="İletişim E-postası"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="İletişim Telefonu"
                    ),
                ),
                (
                    "contact_address",
                    models.TextField(blank=True, verbose_name="İletişim Adresi"),
                ),
                (
                    "contact_form_recipients",
                    models.TextField(
                        blank=True,
                        help_text="Virgülle ayırarak birden fazla e-posta adresi girebilirsiniz",
                        verbose_name="Form Mail Alıcıları",
                    ),
                ),
                (
                    "smtp_host",
                    models.CharField(
                        default="smtp.gmail.com",
                        max_length=255,
                        verbose_name="SMTP Host",
                    ),
                ),
                (
                    "smtp_port",
                    models.IntegerField(default=587, verbose_name="SMTP Port"),
                ),
                (
                    "smtp_username",
                    models.CharField(max_length=255, verbose_name="SMTP Kullanıcı Adı"),
                ),
                (
                    "smtp_password",
                    models.CharField(max_length=255, verbose_name="SMTP Şifre"),
                ),
                (
                    "smtp_use_tls",
                    models.BooleanField(default=True, verbose_name="TLS Kullan"),
                ),
                (
                    "smtp_use_ssl",
                    models.BooleanField(default=False, verbose_name="SSL Kullan"),
                ),
                (
                    "smtp_from_email",
                    models.EmailField(max_length=254, verbose_name="Gönderen E-posta"),
                ),
                (
                    "smtp_from_name",
                    models.CharField(
                        default="Halı Yıkama",
                        max_length=255,
                        verbose_name="Gönderen Adı",
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, verbose_name="Facebook URL"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram URL"),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, verbose_name="Twitter URL"),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="WhatsApp Numarası"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Ayarı",
                "verbose_name_plural": "Site Ayarları",
            },
        ),
    ]
