# Generated by Django 4.2.9 on 2025-10-20 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_sound",
                    models.FileField(
                        blank=True,
                        help_text="Yönetici bildirimleri için ses dosyası (.mp3 formatında)",
                        null=True,
                        upload_to="sounds/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp3"]
                            )
                        ],
                        verbose_name="Bildirim Sesi",
                    ),
                ),
                (
                    "notification_email_enabled",
                    models.BooleanField(
                        default=True, verbose_name="E-posta Bildirimleri Aktif"
                    ),
                ),
                (
                    "notification_sms_enabled",
                    models.BooleanField(
                        default=True, verbose_name="SMS Bildirimleri Aktif"
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        default="Halı Yıkama",
                        max_length=255,
                        verbose_name="İşletme Adı",
                    ),
                ),
                (
                    "business_email",
                    models.EmailField(
                        default="info@haliyikama.com",
                        max_length=254,
                        verbose_name="İşletme E-postası",
                    ),
                ),
                (
                    "business_phone",
                    models.CharField(
                        default="+90 555 123 4567",
                        max_length=20,
                        verbose_name="İşletme Telefonu",
                    ),
                ),
                (
                    "business_address",
                    models.TextField(
                        default="İstanbul, Türkiye", verbose_name="İşletme Adresi"
                    ),
                ),
                (
                    "working_hours_start",
                    models.TimeField(
                        default="09:00", verbose_name="Çalışma Saati Başlangıç"
                    ),
                ),
                (
                    "working_hours_end",
                    models.TimeField(
                        default="18:00", verbose_name="Çalışma Saati Bitiş"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sistem Ayarları",
                "verbose_name_plural": "Sistem Ayarları",
            },
        ),
        migrations.DeleteModel(
            name="ContactFormSubmission",
        ),
        migrations.DeleteModel(
            name="SiteSettings",
        ),
    ]
