# Generated by Django 4.2.9 on 2025-10-20 07:54

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0002_alter_address_options_alter_paymentmethod_options_and_more"),
        (
            "services",
            "0003_alter_bookingsettings_options_alter_category_options_and_more",
        ),
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Rezervasyon",
                "verbose_name_plural": "Rezervasyonlar",
            },
        ),
        migrations.AlterModelOptions(
            name="bookingitem",
            options={
                "ordering": ["id"],
                "verbose_name": "Rezervasyon Kalemi",
                "verbose_name_plural": "Rezervasyon Kalemleri",
            },
        ),
        migrations.AlterModelOptions(
            name="bookingstatushistory",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Rezervasyon Durum Geçmişi",
                "verbose_name_plural": "Rezervasyon Durum Geçmişleri",
            },
        ),
        migrations.AlterModelOptions(
            name="timeslot",
            options={
                "ordering": ["date", "start_time"],
                "verbose_name": "Zaman Aralığı",
                "verbose_name_plural": "Zaman Aralıkları",
            },
        ),
        migrations.AlterField(
            model_name="booking",
            name="admin_notes",
            field=models.TextField(blank=True, verbose_name="Admin Notları"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="assigned_technician",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"user_type": "technician"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_bookings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Atanan Teknisyen",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="booking_number",
            field=models.CharField(
                editable=False,
                max_length=20,
                unique=True,
                verbose_name="Rezervasyon Numarası",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="cancellation_reason",
            field=models.TextField(blank=True, verbose_name="İptal Nedeni"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="İptal Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Tamamlanma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Onaylanma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Oluşturulma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="currency",
            field=models.CharField(
                default="TRY", max_length=3, verbose_name="Para Birimi"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="customer_notes",
            field=models.TextField(blank=True, verbose_name="Müşteri Notları"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="delivery_address",
            field=models.ForeignKey(
                blank=True,
                help_text="If different from pickup",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivery_bookings",
                to="accounts.address",
                verbose_name="Teslim Adresi",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="delivery_date",
            field=models.DateField(blank=True, null=True, verbose_name="Teslim Tarihi"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="delivery_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Teslimat Ücreti",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="delivery_time_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivery_bookings",
                to="bookings.timeslot",
                verbose_name="Teslim Saat Aralığı",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="İndirim"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="pickup_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pickup_bookings",
                to="accounts.address",
                verbose_name="Alım Adresi",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="pickup_date",
            field=models.DateField(verbose_name="Alım Tarihi"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="pickup_time_slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pickup_bookings",
                to="bookings.timeslot",
                verbose_name="Alım Saat Aralığı",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("confirmed", "Confirmed"),
                    ("scheduled", "Scheduled"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Ara Toplam",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Toplam",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Güncellenme Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kullanıcı",
            ),
        ),
        migrations.AlterField(
            model_name="bookingitem",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="bookings.booking",
                verbose_name="Rezervasyon",
            ),
        ),
        migrations.AlterField(
            model_name="bookingitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Oluşturulma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="bookingitem",
            name="line_total",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Satır Toplam"
            ),
        ),
        migrations.AlterField(
            model_name="bookingitem",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notlar"),
        ),
        migrations.AlterField(
            model_name="bookingitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Quantity or square meters",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Miktar",
            ),
        ),
        migrations.AlterField(
            model_name="bookingitem",
            name="subtype",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="services.subtype",
                verbose_name="Alt Kategori",
            ),
        ),
        migrations.AlterField(
            model_name="bookingitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Birim Fiyat"
            ),
        ),
        migrations.AlterField(
            model_name="bookingstatushistory",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="bookings.booking",
                verbose_name="Rezervasyon",
            ),
        ),
        migrations.AlterField(
            model_name="bookingstatushistory",
            name="changed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Değiştiren",
            ),
        ),
        migrations.AlterField(
            model_name="bookingstatushistory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Değiştirme Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="bookingstatushistory",
            name="new_status",
            field=models.CharField(max_length=20, verbose_name="Yeni Durum"),
        ),
        migrations.AlterField(
            model_name="bookingstatushistory",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notlar"),
        ),
        migrations.AlterField(
            model_name="bookingstatushistory",
            name="old_status",
            field=models.CharField(max_length=20, verbose_name="Eski Durum"),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Oluşturulma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="current_bookings",
            field=models.IntegerField(default=0, verbose_name="Mevcut Rezervasyonlar"),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="date",
            field=models.DateField(verbose_name="Tarih"),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="end_time",
            field=models.TimeField(verbose_name="Bitiş Saati"),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="is_available",
            field=models.BooleanField(default=True, verbose_name="Müsait"),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="max_capacity",
            field=models.IntegerField(default=5, verbose_name="Maksimum Kapasite"),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="start_time",
            field=models.TimeField(verbose_name="Başlangıç Saati"),
        ),
    ]
