# Generated by Django 4.2.9 on 2025-10-21 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_alter_booking_options_alter_bookingitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="pickup_time_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pickup_bookings",
                to="bookings.timeslot",
                verbose_name="Alım Saat Aralığı",
            ),
        ),
    ]
