# Generated by Django 4.2.9 on 2025-10-20 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_alter_booking_options_alter_bookingitem_options_and_more"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new_order", "New Order"),
                            ("cancelled_order", "Cancelled Order"),
                            ("status_change", "Status Change"),
                            ("info", "Information"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_notifications",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "admin notification",
                "verbose_name_plural": "admin notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_read", "created_at"],
                        name="notificatio_is_read_693f9f_idx",
                    )
                ],
            },
        ),
    ]
