# Generated by Django 4.2.9 on 2025-10-21 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_alter_booking_options_alter_bookingitem_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0003_fcmdevice"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("order_confirmed", "Order Confirmed"),
                            ("order_in_progress", "Order In Progress"),
                            ("order_completed", "Order Completed"),
                            ("order_cancelled", "Order Cancelled"),
                            ("info", "Information"),
                        ],
                        default="info",
                        max_length=30,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_notifications",
                        to="bookings.booking",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user notification",
                "verbose_name_plural": "user notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "created_at"],
                        name="notificatio_user_id_319bc5_idx",
                    )
                ],
            },
        ),
    ]
